name: Sync Fork

on:
  schedule:
    - cron: "0 * * * *" # Runs at 00:00 every Sunday
  workflow_dispatch: # on button click

permissions:
  contents: write
  pull-requests: write

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git identity
        run: |
          git config --global user.name "Dan via GitHub Actions"
          git config --global user.email "dan.chapman@grip.co.nz"

      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          ref: linz-basemaps-syncd # Adjust if your branch is named differently

      - name: Fetch changes from the original repository
        run: |
          git remote add upstream https://github.com/linz/basemaps.git
          git fetch upstream master
          git checkout linz-basemaps-syncd 
          git merge upstream/master --allow-unrelated-histories

      - name: Push changes to the fork
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: linz-basemaps-syncd # Adjust if your branch is named differently
